title: Archivo Hispano
description: Archivo digital de escritos políticos, filosóficos y literarios de autores hispanos
remote_theme: just-the-docs/just-the-docs
search_enabled: true
color_scheme: light
