blank_issues_enabled: true
contact_links:
  - name: Preguntas Generales / General Questions
    url: https://github.com/archivohispano/archivohispano.github.io/discussions
    about: Ask questions and discuss with the community
